export const ADD_LOGIN_GET_REQUEST = 'ADD_LOGIN_GET_REQUEST';
export const ADD_LOGIN_GET_SUCCESS = 'ADD_LOGIN_GET_SUCCESS';
export const ADD_LOGIN_GET_FAIL = 'ADD_LOGIN_GET_FAIL';

export const SIGNUP_GET_REQUEST = 'SIGNUP_GET_REQUEST';
export const SIGNUP_GET_SUCCESS = 'SIGNUP_GET_SUCCESS';
export const SIGNUP_GET_FAIL = 'SIGNUP_GET_FAIL';

export const OTP_GET_REQUEST = 'OTP_GET_REQUEST';
export const OTP_GET_SUCCESS = 'OTP_GET_SUCCESS';
export const OTP_GET_FAIL = 'OTP_GET_FAIL';




